Add isearch-{beginning,end}-of-buffer commands
kickingvegas/casual pull request #44
Opened 2024-10-23 11:18 UTC by deejayem

Having `isearch-beginning-of-buffer` and `isearch-end-of-buffer` in `casual-isearch-tmenu` seems useful to me, so here's a PR to add them. I don't mind at all if you don't want to merge this, as it's easy enough to add them in my own config with `transient-append-suffix`.

I don't know how to test the `:description` part, but hopefully it works okay (I copied the db entries from `casual-info-utils`). 

Thank you for making these packages!

2024-10-23 17:41 UTC, kickingvegas requested changes
Thanks for submitting this PR! I like this enhancement. Will request a couple changes.

2024-10-23 17:49 UTC, kickingvegas requested changes
Please update the unit-test `test-casual-isearch-tmenu` with the two new commands you've introduced.

https://github.com/kickingvegas/casual/blob/main/tests/test-casual-isearch.el

2024-10-23 17:49 UTC, kickingvegas commented on lisp/casual-isearch-utils.el
> +  '((:first . '("⏮️" "First"))
Use "⤒" instead of "⏮️" to be consistent with `casual-bookmarks-unicode-db`.

2024-10-23 17:49 UTC, kickingvegas commented on lisp/casual-isearch-utils.el
> +    (:previous . '("↑" "Previous"))
Use "⤓" instead of "⏭️" to be consistent with `casual-bookmarks-unicode-db`.

2024-10-23 17:53 UTC, kickingvegas reviewed
Another test to modify. Thanks!

2024-10-23 17:53 UTC, kickingvegas commented on lisp/casual-isearch-utils.el
>      (:next . '("↓" "Next")))
Please modify `test-casual-isearch-unicode-get` to support testing these changes.

https://github.com/kickingvegas/casual/blob/main/tests/test-casual-isearch-utils.el

2024-10-24 11:37 UTC, deejayem commented
Thank you for the feedback.

I've made the requested changes, but couldn't get the tests working (with or without my changes), so haven't been able to verify that they pass.

2024-10-24 15:58 UTC, kickingvegas approved these changes
Thanks for making the changes!

2024-10-24 16:01 UTC, kickingvegas commented
There's a bit of setup/surgery you need to do in your emacs elpa directory to get the tests working. Don't worry about it, I just wanted to have the affected tests instrumented. They pass regression here.

2024-10-24 16:01 UTC, merged

2024-10-24 18:30 UTC, kickingvegas commented
@deejayem https://github.com/kickingvegas/casual/releases/tag/2.0.7 is out in the wild. Should be on MELPA about two hours from this post. Thanks much!